#! /bin/sh
#
# RTEMS Tools Project (http://www.rtems.org/)
# Copyright 2017,2019 Chris Johns (chrisj@rtems.org)
# All rights reserved.
#
# This file is part of the RTEMS Tools package in 'rtems-tools'.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

set -e

#
# This worker script to build the release notes.
#

#
# Defaults.
#
. ${release_top}/rtems-release-defaults

#
# Only build if wkhtmltopdf is present on the system.
#
if [ "`command -v wkhtmltopdf`"no = no ]; then
 echo "warning: release notes not built: no wkhtmltopdf"
 exit 0
fi

#
# Only build if gs is present on the system.
#
if [ "`command -v gs`"no = no ]; then
 echo "warning: release notes not built: no gs"
 exit 0
fi

#
# Common package start. No git repo the data source is Trac.
#
rtems_git_repo=no
title="RTEMS Release Notes builder"
. ./rtems-release-package-start

#
# The workspace pwd
#
ws_pwd=${PWD}

echo "] Creating release notes for ${release}"
echo "] Generate release notes markdown"

rn_name=rtems-${release}-release-notes

#
# The release notes are taken directly from Gitlab
#
${top}/release-notes/rtems-release-notes \
      --config=../../../config.ini \
      --fetch \
      --write ${rn_name}.json \
      --milestone ${version}.${revision_no}

#
# Move the HTML into the release
#
mv build/html ../${rn_name}
mv build/latex/rtems-release-notes-${version}.${revision_no}.pdf ../${rn_name}.pdf
mv ${rn_name}.json ../${rn_name}.json
xz ../${rn_name}.json

#
# Comman package end.
#
. ${top}/rtems-release-package-end

exit 0
