#! /bin/sh
#
# RTEMS Tools Project (http://www.rtems.org/)
# Copyright 2015,2016,2019 Chris Johns (chrisj@rtems.org)
# All rights reserved.
#
# This file is part of the RTEMS Tools package in 'rtems-tools'.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

set -e

#
# Defaults.
#
. ${release_top}/rtems-release-defaults

#
# The package, version, revision and release URL.
#
if [ $# -ne 5 ]; then
    echo "error: must be arguments, the package, version," \
	 "release, release URL and the top directory."
 exit 1
fi
package=$1
version=$2
revision=$3
release_url=$4
toptop=$5

. ${release_top}/rtems-release-version

#
# Get the RSB packages hashes creating doing this release
#
. ${pkg_list}

prefix=${package}-${release}

echo "] RTEMS Release RSB Versioning, v${release}"
echo "] Package: ${package}"
echo "] Release: ${release}"

#
# Get the release sources path and add it to the VERSION.
#
. ${release_top}/rtems-release-path
echo "release_path = ${rtems_release_sources}" >> ${prefix}/VERSION

checksum=sha512

#
# Add the hashes for the required packages in the RSB generated during an RTEMS
# release.
#
echo >> ${prefix}/VERSION
echo "[hashes]" >> ${prefix}/VERSION
for p in ${rtems_rsb_hash_pkgs}
do
  file=${p}.tar.xz
  hash=$(${checksum} -q ${toptop}/${release}/${file})
  echo "${file} = ${checksum} ${hash}" >> ${prefix}/VERSION
done

echo "] RSB Versioning complete."

exit 0
