#! /bin/sh
#
# RTEMS Tools Project (http://www.rtems.org/)
# Copyright 2016 Chris Johns (chrisj@rtems.org)
# All rights reserved.
#
# This file is part of the RTEMS Tools package in 'rtems-tools'.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

set -e

#
# This is the top level RTEMS release script. Supply the version and and the
# release.
#

#
# Defaults.
#
. ${release_top}/rtems-release-defaults

#
# Global release top path.
#
export release_top=$(realpath $(dirname $0))
cd ${release_top}

#
# The user, version and revision.
#
#
# Usage for this tool.
#
usage() {
 echo "Usage: $0 [-t] [-p] user release version" 1>&2
 echo " where:" 1>&2
 echo "  user         : Your git user name" 1>&2
 echo "  version      : The version of RTEMS, eg 5" 1>&2
 echo "  revision     : The revision, eg 0.0 or 0.0-myrev" 1>&2
 echo "  -p           : Push the changes." 1>&2
 exit 1
}

#
# Option defaults
#
clone_url=
push=no

#
# Manage the command line.
#
while getopts "tp" opt; do
 case "${opt}" in
  t)
   clone_url=git://git.rtems.org
   ;;
  p)
   push=yes
   ;;
  *)
   usage
   ;;
 esac
done

shift $((OPTIND-1))
if [ $# -ne 3 ]; then
 echo "error: must be 3 arguments, your git user name, version and the release. See -h for help"
 exit 1
fi

user=$1
version=$2
revision=$3

. ./rtems-release-version

echo "] RTEMS Release Tag, v${release}"

#
# Check if clone_url is empty.
#
if [ -z "${clone_url}" ]; then
 clone_url=ssh://${user}@dispatch.rtems.org/data/git
fi

#
# The tagging workspace.
#
ws_tag=${release}-tagged

#
# Version configuration. Overrides defaults.
#
if [ -f rtems-release-${version}-conf ]; then
 rtems_release_conf=rtems-release-${version}-conf
 . rtems-release-${version}-conf
fi

#
# Clean the tagging directory away.
#
rm -rf ${ws_tag}
mkdir ${ws_tag}

#
# Clone and tag the repositories.
#
cd ${ws_tag}
 for r in ${rtems_repos}
 do
  ref=origin/${version}
  echo "git clone ${clone_url}/${r} ${r}"
  git clone ${clone_url}/${r} ${r}
  cd ${r}
   echo "git tag ${release} ${ref}"
   git tag ${release} ${ref}
   cd ..
 done

 if [ ${push} = yes ]; then
  for r in ${rtems_repos}
  do
   cd ${r}
    echo "git push origin ${release}"
    git push origin ${release}
    cd ..
  done
 fi
 cd ..

exit 0
